# Generated by Django 4.2 on 2023-04-23 11:15

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import upload_file.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('logo', models.ImageField(null=True, upload_to=upload_file.models.user_image)),
                ('files', models.FileField(null=True, upload_to=upload_file.models.user_files, validators=[django.core.validators.FileExtensionValidator(['txt', 'pdf'], message='fiels должен быть формата txt или pdf')])),
                ('video', models.FileField(null=True, upload_to=upload_file.models.user_video)),
                ('info', models.CharField(max_length=500, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'элемент',
                'verbose_name_plural': 'элементы',
                'db_table': 'item',
            },
        ),
    ]
